name: app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  google_fonts: ^3.0.1
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  fluttertoast: ^8.1.1
  cloud_firestore: ^4.1.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  firebase_storage: ^11.0.10
  file_picker: ^5.2.5
  geolocator: ^9.0.2
  geocoding: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/doctor.png
    - assets/images/medicine.png
    - assets/images/report.png
    - assets/images/icon1.png
    - assets/images/icon2.png
    - assets/images/icon3.png
    - assets/images/icon4.png
    - assets/images/icon5.png
    - assets/images/icon6.png
    - assets/images/icon7.png
    - assets/images/icon8.png
    - assets/images/symp/1.png
    - assets/images/symp/2.png
    - assets/images/symp/3.png
    - assets/images/symp/4.png
    - assets/images/symp/5.png
    - assets/images/symp/6.png
    - assets/images/symp/7.png
    - assets/images/symp/8.png
    - assets/images/symp/9.png
    - assets/images/symp/10.png
    - assets/images/symp/11.png
    - assets/images/symp/12.png
    - assets/images/symp/13.png
    - assets/images/symp/14.png
    - assets/images/symp/15.png
    - assets/images/symp/16.png
    - assets/images/symp/17.png
    - assets/images/symp/18.png
    - assets/images/symp/19.png
    - assets/images/symp/20.png
    - assets/images/symp/21.png
    - assets/images/symp/22.png
    - assets/images/symp/23.png
    - assets/images/symp/24.png
    - assets/images/symp/25.png
    - assets/images/symp/26.png
    - assets/images/symp/27.png
    - assets/images/symp/28.png
    - assets/images/symp/29.png
    - assets/images/symp/30.png
    - assets/images/symp/31.png

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/lexend_deca.ttf

    - family: Poppins
      fonts:
       - asset: assets/fonts/Poppins-Regular.ttf

    - family: Outfit
      fonts:
       - asset: assets/fonts/Outfit-Regular.ttf

    - family: pbold
      fonts:
       - asset: assets/fonts/pbold.ttf