name: app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  google_fonts: ^3.0.1
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  fluttertoast: ^8.1.1
  cloud_firestore: ^4.1.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  firebase_storage: ^11.0.10
  file_picker: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/default.jpg
    - assets/1.jpg
    - assets/2.jpg
    - assets/3.jpg

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins-Regular.ttf

   - family: Outfit
     fonts:
       - asset: assets/fonts/Outfit-Regular.ttf

   - family: pbold
     fonts:
       - asset: assets/fonts/pbold.ttf